### ISSUE TITLE
Module Installation

### ISSUE THREAD

**Issue by krebeck** [SFULibrary/islandora_doi_framework#12]
I'm having trouble making the "DOI" subtab appear under each object's "Manage" tab.  I have cloned the module, enabled the Islandora DOI DataCite, Islandora DOI Framework, and Islandora DOI MODS modules and submodules, granted the proper permissions, and configured my DataCite with our credentials.  But I see no sub tab on my documents, citations, or other content types.

Am I missing something simple (entirely possible)?

**Comment by mjordan** [comment]
Since the tab is a type of menu item, can I ask you to clear your cache to see if there is any effect?

**Comment by krebeck** [comment]
Sure thing.  It doesn't seem to have helped.  Here's a screenshot of my current menus.
![image](https://user-images.githubusercontent.com/12201980/33676585-1aa305fe-da84-11e7-9170-8ec628532ada.png)

**Comment by mjordan** [comment]
OK, thanks, I'll take a closer look.

**Comment by mjordan** [comment]
@krebeck to eliminate any theming weirdness that might be occurring, can you go to the tab's menu path to see what happens, e.g. `islandora/object/your:pid/manage/assign_doi`? If you get a 404, the menu item is not registered; if you get an access denied, it's permissions; if you get a form that allow you assign a DOI, it's theming.

**Comment by krebeck** [comment]
Okay, it must be permissions then.  I get an access denied.  This is my test server so I've gone ahead and given the Islandora DOI Framework to all authenticated users.  Could permissions error also include incorrect credentials for DataCite configuration?  I'm wondering if our institutional repository librarian doesn't have the right password.

**Comment by mjordan** [comment]
Congratulations @krebeck, you've found a bug! The menu access arguement at https://github.com/mjordan/islandora_doi_framework/blob/7.x/islandora_doi_framework.module#L15 doesn't match the permission defined at https://github.com/mjordan/islandora_doi_framework/blob/7.x/islandora_doi_framework.module#L29. Sloppiness on my part. I'll push a fix by tomorrow morning and ask you to pull in the update and test. Sorry about that.

**Comment by mjordan** [comment]
Or - feel free to open a PR to do that, and I'll test.

**Comment by krebeck** [comment]
Thanks so much.  I probably won't get to it before you will as it's "make a mad dash to childcare" time here on the East Coast.  But I'll be happy to test in the AM.

**Comment by mjordan** [comment]
OK, I'll fix and open a PR this ~evening~ today.

**Comment by krebeck** [comment]
Was this fix pushed and do you need me to pull in for testing?  Let me know if I can help.

**Comment by mjordan** [comment]
@krebeck yes, I pushed a fix, it would be great if you could test it following the procedure outlined in the PR .

**Comment by mjordan** [comment]
Fix merged with 6bcd58a142695b3d9c19fcdf4b2a63e21aa095dd.
