### ISSUE TITLE
404 response

### ISSUE THREAD

**Issue by bondjimbond** [SFULibrary/islandora_doi_framework#15]
I recently got credentials for my test account at the new DataCite. Trying to register a DOI with them in my local Vagrant machine, I get an error:

> Error registering metadata for object islandora:4, so cannot mint DOI: 404, Not Found

Using the default settings for everything but my credentials. Any idea what the problem is?

**Comment by mjordan** [comment]
@bondjimbond, @axfelix has this working here. Maybe he can advise.

**Comment by axfelix** [comment]
Hi, just back from vacation, sorry for the delay.

Right now my config looks like this:

<img width="510" alt="doi" src="https://user-images.githubusercontent.com/252047/76235319-2e944f80-61e8-11ea-8c20-aa1b6e4d5c21.png">

I've confirmed that it also still works with the new DataCite endpoints, though this still reflects the old environment. I don't think I've ever used PID-based assignment in production as our PIDs are not meaningful -- not sure if you've tested UUIDs.
