### ISSUE TITLE
Add islandora_doi_ddi module

### ISSUE THREAD

**Issue by axfelix** [SFULibrary/islandora_doi_framework#2]
Because our Islandora repository uses DDI rather than MODS, it's preferable for us to get an islandora_doi_ddi module along the lines of islandora_doi_mods merged into this repo upstream, so that it doesn't deviate. Interactions with DDI should be basically identical to interactions with MODS.

**Comment by mjordan** [comment]
Sounds good. Will take care of tonight.

**Comment by mjordan** [comment]
OK, links between repos in all READMEs updated.
