### ISSUE TITLE
Other modules need to be able to define required required fields in DataCite XML

### ISSUE THREAD

**Issue by mjordan** [SFULibrary/islandora_doi_framework#6]
As @axfelix points out in https://github.com/mjordan/islandora_doi_sfu/issues/1, the hard-coded list of required values at https://github.com/mjordan/islandora_doi_framework/blob/7.x/modules/islandora_doi_datacite/includes/utilities.inc#L240 should be overridable by modules that add a GUI for allowing user input for DataCite values, and possibly other use cases.

I think having Islandora DOI DataCite provide a hook that allows other modules to alter this list is probably the most standardized way to go.

**Comment by mjordan** [comment]
Just cross-referencing here, but I've asked @axfelix to test this over at https://github.com/mjordan/islandora_doi_sfu/issues/1.

**Comment by mjordan** [comment]
Reminder to self: if the addition of the hook_alter works, create a islandora_doi_datacite.api.php file to document it.

**Comment by axfelix** [comment]
Would you be opposed to my adding a hook here:

https://github.com/axfelix/islandora_doi_framework/blob/issue-6/modules/islandora_doi_datacite/includes/utilities.inc#L251

Along the lines of "if creator / publisher / date aren't filled and object is a collection, tally up the values of those fields in all of this collection's immediate children, and inherit the most common values as long as they each appear more than once"?

I was going to add this to the SFU customizations but I think it's just as useful here because the use case of "wanting to add a DOI to a collection" is going to be relatively common in accordance with best practices around DOIs for "studies" rather than individual objects, and Islandora collections generally do not have those values.

**Comment by axfelix** [comment]
Actually, crap, there doesn't seem to be a getChildren API method. Could I even reverse-construct that from the RELS-EXT, or does it only go upwards?

**Comment by mjordan** [comment]
It only goes upwards. You can call https://github.com/Islandora/islandora_solution_pack_collection/blob/7.x/islandora_basic_collection.module if you want to get all immediate members of a collection.

**Comment by axfelix** [comment]
Thanks! Assuming you've used it before (if you haven't, just tell me and I can play around myself):

I assume the easiest thing for me to use here is islandora_basic_collection_get_member_objects?
Is that generally bootstrapped into any Islandora module so I don't need to worry about trying to require_once it? I still basically have no grasp of PHP library importing.
It says it returns tuples -- do those look like $object, or ... ?

**Comment by mjordan** [comment]
No, I don't think it would be in scope unless you were browsing a collection page. Use the following to bring it in, just before you call it:

`module_load_include('module', 'islandora_solution_pack_collection', 'islandora_basic_collection');`

**Comment by mjordan** [comment]
Sorry, the link in my previous comment somehow got truncated. It should have been https://github.com/Islandora/islandora_solution_pack_collection/blob/7.x/islandora_basic_collection.module#L645. I don't know what tuples refers to here, it's not a structure that's native to PHP, by that name anyway. If you have the devel module installed, I'd just `dd()` the output of the function to see what you get.

**Comment by axfelix** [comment]
OK, will do, thanks!

**Comment by mjordan** [comment]
Forgot to mention, output of `dd()` gets written to `/tmp/drupal_debug.txt`.

**Comment by axfelix** [comment]
OK, say I made some small changes and it's 500-ing without logs, what's the best place to start to try to resolve that if I have no perceptible syntax errors?

**Comment by mjordan** [comment]
There's nothing in the apache error log?

**Comment by axfelix** [comment]
No, and log levels should be fine... I'll fuss with it some more.

**Comment by mjordan** [comment]
Dumb question, but are you sure Islandora is 500ing, or, if you're hitting the DataCite API endpoint, could it be 500ing and the error bubbling up to where you can see it?

**Comment by mjordan** [comment]
Closing this since work in the 'rewrite' branch resolves this issue.
